name: build

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_COMPOSE_FILE_NAME: docker-compose.yml
  DOCKERFILE: Dockerfile

jobs:
  build:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v4

    - name: Install docker
      run: brew install docker

    - name: Build Dockerfile
      run: docker buildx build . --platform linux/amd64
      # run: COMPOSE_DOCKER_CLI_BUILD=1 docker compose build
