name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_COMPOSE_FILE_NAME: docker-compose.yml

jobs:
  build:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
