name: build

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_COMPOSE_FILE_NAME: docker-compose.yml
  DOCKERFILE: Dockerfile

jobs:
  build:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v4

    - name: Install docker
      run: |
        brew install --cask docker virtualbox
        brew install docker-compose docker-buildx docker-machine
        docker-machine create --driver virtualbox default
        docker-machine restart

    - name: Build Dockerfile
      # run: docker buildx build .
      run: COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build
