name: Live View Pipeline

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_TOOLCHAIN_FILE: /Users/$ENV{USER}/Library/vcpkg/scripts/buildsystems/vcpkg.cmake
  CMAKE_PREFIX_PATH: /Users/$ENV{USER}/Library/vcpkg/installed/arm64-osx/share

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest

    - name: Restore from cache and setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

